Create action "ADD project" for redux #12
tomaszprc/timelog_selleo pull request #17
Opened 2021-02-24 13:33 UTC by tomaszprc

2021-02-25 11:03 UTC, korczas requested changes
update CSS props sorting.

2021-02-25 11:03 UTC, korczas commented on src/styles/components/_button.scss
> +  cursor: pointer;
let's go with asc sorting ;)

2021-02-25 11:03 UTC, korczas commented on src/styles/components/_button.scss
> +  }
What do you think about using more generic class names, like: primary, secondary, tertiary, success, fail, etc.

2021-02-25 12:55 UTC, tomaszprc commented on src/components/Button/Button.tsx
> +      }`}
Moved to another jira. 
https://github.com/tomaszprc/timelog_selleo/issues/20

2021-02-25 12:56 UTC, merged

2021-02-26 11:05 UTC, korczas commented on src/redux/projects/reducers.ts
> +      const id = projectsList[projectsList.length - 1].id + 1;
`const id = projectsList[projectsList.length - 1]?.id + 1 || 0;`

2021-02-26 11:05 UTC, korczas commented on src/redux/projects/types.ts
> +export type AddProjectPayload = Omit<Project, "id" | "timeTrackerIds">;
I know I wrote this, but in this case is better to use 
```
export type AddProjectPayload = Pick<Project, "title" | "description">;
```

2021-02-26 11:05 UTC, korczas commented on src/redux/projects/types.ts
> +  openModal: boolean;
not used anywhere

2021-02-26 11:59 UTC, tomaszprc commented on src/redux/projects/actions.ts
> +  // request do bazy => baza zwraca async payload => payload zwracasz w return
I leave it for my note, it can be helpful in future when I work with DB.